# Generated by Django 3.2.15 on 2022-10-08 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20221005_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProjectTask',
            new_name='User_Project_Task',
        ),
        migrations.AlterModelOptions(
            name='user_project_task',
            options={'ordering': ['-id'], 'verbose_name': 'User_Project_Task', 'verbose_name_plural': 'User_Project_Tasks'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_date',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='second_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
