# Generated by Django 3.2.15 on 2022-11-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221107_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline',
            new_name='todo_date',
        ),
        migrations.DeleteModel(
            name='User_Project_Task',
        ),
    ]
