# Generated by Django 3.2.15 on 2022-12-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20221127_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_project_task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
