# Generated by Django 3.2.15 on 2022-12-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
